export const CUSTOMER_LIST_REQUEST = 'CUSTOMER_LIST_REQUEST'
export const CUSTOMER_LIST_SUCCESS = 'CUSTOMER_LIST_SUCCESS'
export const CUSTOMER_LIST_FAIL = 'CUSTOMER_LIST_FAIL'

export const CUSTOMER_DETAILS_REQUEST = 'CUSTOMER_DETAILS_REQUEST'
export const CUSTOMER_DETAILS_SUCCESS = 'CUSTOMER_DETAILS_SUCCESS'
export const CUSTOMER_DETAILS_FAIL = 'CUSTOMER_DETAILS_FAIL'

export const CUSTOMER_DELETE_REQUEST = 'CUSTOMER_DELETE_REQUEST'
export const CUSTOMER_DELETE_SUCCESS = 'CUSTOMER_DELETE_SUCCESS'
export const CUSTOMER_DELETE_SUCCESS_REFRESH = 'CUSTOMER_DELETE_SUCCESS_REFRESH'
export const CUSTOMER_DELETE_FAIL = 'CUSTOMER_DELETE_FAIL'

export const CUSTOMER_CREATE_REQUEST = 'CUSTOMER_CREATE_REQUEST'
export const CUSTOMER_CREATE_SUCCESS = 'CUSTOMER_CREATE_SUCCESS'
export const CUSTOMER_CREATE_FAIL = 'CUSTOMER_CREATE_FAIL'
export const CUSTOMER_CREATE_RESET = 'CUSTOMER_CREATE_RESET'

export const CUSTOMER_UPDATE_REQUEST = 'CUSTOMER_UPDATE_REQUEST'
export const CUSTOMER_UPDATE_SUCCESS = 'CUSTOMER_UPDATE_SUCCESS'
export const CUSTOMER_UPDATE_SUCCESS_REFRESH = 'CUSTOMER_UPDATE_SUCCESS_REFRESH'
export const CUSTOMER_UPDATE_FAIL = 'CUSTOMER_UPDATE_FAIL'
export const CUSTOMER_UPDATE_RESET = 'CUSTOMER_UPDATE_RESET'

export const CUSTOMER_CREATE_REVIEW_REQUEST = 'CUSTOMER_CREATE_REVIEW_REQUEST'
export const CUSTOMER_CREATE_REVIEW_SUCCESS = 'CUSTOMER_CREATE_REVIEW_SUCCESS'
export const CUSTOMER_CREATE_REVIEW_FAIL = 'CUSTOMER_CREATE_REVIEW_FAIL'
export const CUSTOMER_CREATE_REVIEW_RESET = 'CUSTOMER_CREATE_REVIEW_RESET'

export const CUSTOMER_TOP_REQUEST = 'CUSTOMER_TOP_REQUEST'
export const CUSTOMER_TOP_SUCCESS = 'CUSTOMER_TOP_SUCCESS'
export const CUSTOMER_TOP_FAIL = 'CUSTOMER_TOP_FAIL'
